name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: SonarCloud Scan
        run: |
          mvn -B verify sonar:sonar -DskipTests=true \
            -Dsonar.projectKey=fer8955_baseSelenium \
            -Dsonar.organization=fer8955 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  selenium-tests:
    runs-on: ubuntu-latest
    needs: []   # Corre en paralelo al job 'sonar'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # --- Instalar Google Chrome ---
      - name: Install Chrome
        uses: browser-actions/install-chrome@v1

      # --- Instalar ChromeDriver ---
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Verificar instalación (opcional pero útil)
      - name: Check browser versions
        run: |
          google-chrome --version
          chromedriver --version

      # Ejecutar Selenium tests
      - name: Run Selenium Tests
        run: mvn -B test
